2021-04-22T13:30:09.491+0800	[35mDEBUG[0m	dialtesting	dialtesting/dialer.go:63	dialer: &dialtesting.dialer{task:(*dialtesting.HTTPTask)(0xc0004de300), ticker:(*time.Ticker)(0xc0006a8050), initTime:time.Time{wall:0xc01860585d412e78, ext:1027960885, loc:(*time.Location)(0x3e24800)}, testCnt:0, class:"", tags:map[string]string(nil), updateCh:(chan dialtesting.Task)(0xc0006aa000), failCnt:0}
--- FAIL: TestDialer (2.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1526a8a]

goroutine 50 [running]:
testing.tRunner.func1(0xc000302200)
	/usr/local/Cellar/go@1.13/1.13.15/libexec/src/testing/testing.go:874 +0x3a3
panic(0x249a880, 0x3e00280)
	/usr/local/Cellar/go@1.13/1.13.15/libexec/src/runtime/panic.go:679 +0x1b2
gitlab.jiagouyun.com/cloudcare-tools/datakit/io.(*IO).DoFeed(0x0, 0xc00000e190, 0x1, 0x1, 0x2820b61, 0x11, 0x2812976, 0xb, 0xc0006a63f0, 0x1, ...)
	/Users/admin/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit/io/io.go:121 +0x3a
gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting.Feed(0x2812976, 0xb, 0x2820b61, 0x11, 0xc00000e188, 0xc0006a63f0, 0x11, 0xc00000e188)
	/Users/admin/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting/io.go:47 +0xd9
gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting.(*dialer).feedIo(0xc00031a3c0, 0x0, 0x0)
	/Users/admin/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting/dialer.go:127 +0x4e4
gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting.(*dialer).run(0xc00031a3c0, 0x0, 0x0)
	/Users/admin/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting/dialer.go:80 +0x53d
gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting.TestDialer(0xc000302200)
	/Users/admin/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting/dialer_test.go:39 +0x39a
testing.tRunner(0xc000302200, 0x28e1460)
	/usr/local/Cellar/go@1.13/1.13.15/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go@1.13/1.13.15/libexec/src/testing/testing.go:960 +0x350
FAIL	gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/dialtesting	2.738s
FAIL
ok  	gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/disk	5.552s	coverage: 68.6% of statements
2021-04-22T13:30:22.018+0800	[31mERROR[0m	docker	docker/metric.go:27	Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
--- FAIL: TestMain (0.00s)
    input_test.go:26: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-04-22T13:30:22.018+0800	[31mERROR[0m	docker	docker/log.go:76	Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
FAIL
coverage: 5.8% of statements
FAIL	gitlab.jiagouyun.com/cloudcare-tools/datakit/plugins/inputs/docker	5.548s
FAIL
